config/routes.rb
require 'resque_web'

Rails.application.routes.draw do

  resources :turns

  resources :regions

  resources :local_participation_records

  resources :boards

  resources :users

  root 'boards#show'

  mount ResqueWeb::Engine => '/resque_web'

end

app/models/local_participation_record.rb
class LocalParticipationRecord < ActiveRecord::Base
  belongs_to :board
  belongs_to :user

  after_commit { LocalParticipationRecordRelayJob.perform_later(self) }
end

app/controllers/local_participation_records_controller.rb
class LocalParticipationRecordsController < ApplicationController
  before_action :set_local_participation_record, only: [:show, :edit, :update, :destroy]

  # GET /local_participation_records
  # GET /local_participation_records.json
  def index
    @local_participation_records = LocalParticipationRecord.all
  end

  # GET /local_participation_records/1
  # GET /local_participation_records/1.json
  def show
  end

  # GET /local_participation_records/new
  def new
    @local_participation_record = LocalParticipationRecord.new
  end

  # GET /local_participation_records/1/edit
  def edit
  end

  # POST /local_participation_records
  # POST /local_participation_records.json
  def create
    @local_participation_record = LocalParticipationRecord.new(local_participation_record_params)

    respond_to do |format|
      if @local_participation_record.save
        format.html { redirect_to @local_participation_record, notice: 'Local participation record was successfully created.' }
        format.json { render :show, status: :created, location: @local_participation_record }
      else
        format.html { render :new }
        format.json { render json: @local_participation_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /local_participation_records/1
  # PATCH/PUT /local_participation_records/1.json
  def update
    respond_to do |format|
      if @local_participation_record.update(local_participation_record_params)
        format.html { redirect_to @local_participation_record, notice: 'Local participation record was successfully updated.' }
        format.json { render :show, status: :ok, location: @local_participation_record }
      else
        format.html { render :edit }
        format.json { render json: @local_participation_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /local_participation_records/1
  # DELETE /local_participation_records/1.json
  def destroy
    @local_participation_record.destroy
    respond_to do |format|
      format.html { redirect_to local_participation_records_url, notice: 'Local participation record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_local_participation_record
      @local_participation_record = LocalParticipationRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def local_participation_record_params
      params.require(:local_participation_record).permit(:user_id, :board_id, :num_moves, :num_invites, :xpos, :ypos)
    end
end

app/helpers/local_participation_records_helper.rb
module LocalParticipationRecordsHelper
end

app/views/local_participation_records/_form.html.erb
<%= form_for(@local_participation_record) do |f| %>
  <% if @local_participation_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@local_participation_record.errors.count, "error") %> prohibited this local_participation_record from being saved:</h2>

      <ul>
      <% @local_participation_record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :board_id %><br>
    <%= f.number_field :board_id %>
  </div>
  <div class="field">
    <%= f.label :num_moves %><br>
    <%= f.number_field :num_moves %>
  </div>
  <div class="field">
    <%= f.label :num_invites %><br>
    <%= f.number_field :num_invites %>
  </div>
  <div class="field">
    <%= f.label :xpos %><br>
    <%= f.number_field :xpos %>
  </div>
  <div class="field">
    <%= f.label :ypos %><br>
    <%= f.number_field :ypos %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/local_participation_records/edit.html.erb
<h1>Editing Local Participation Record</h1>

<%= render 'form' %>

<%= link_to 'Show', @local_participation_record %> |
<%= link_to 'Back', local_participation_records_path %>

app/views/local_participation_records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Local Participation Records</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Board</th>
      <th>Num moves</th>
      <th>Num invites</th>
      <th>Xpos</th>
      <th>Ypos</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @local_participation_records.each do |local_participation_record| %>
      <tr>
        <td><%= local_participation_record.user_id %></td>
        <td><%= local_participation_record.board_id %></td>
        <td><%= local_participation_record.num_moves %></td>
        <td><%= local_participation_record.num_invites %></td>
        <td><%= local_participation_record.xpos %></td>
        <td><%= local_participation_record.ypos %></td>
        <td><%= link_to 'Show', local_participation_record %></td>
        <td><%= link_to 'Edit', edit_local_participation_record_path(local_participation_record) %></td>
        <td><%= link_to 'Destroy', local_participation_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Local participation record', new_local_participation_record_path %>

app/views/local_participation_records/new.html.erb
<h1>New Local Participation Record</h1>

<%= render 'form' %>

<%= link_to 'Back', local_participation_records_path %>

app/views/local_participation_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @local_participation_record.user_id %>
</p>

<p>
  <strong>Board:</strong>
  <%= @local_participation_record.board_id %>
</p>

<p>
  <strong>Num moves:</strong>
  <%= @local_participation_record.num_moves %>
</p>

<p>
  <strong>Num invites:</strong>
  <%= @local_participation_record.num_invites %>
</p>

<p>
  <strong>Xpos:</strong>
  <%= @local_participation_record.xpos %>
</p>

<p>
  <strong>Ypos:</strong>
  <%= @local_participation_record.ypos %>
</p>

<%= link_to 'Edit', edit_local_participation_record_path(@local_participation_record) %> |
<%= link_to 'Back', local_participation_records_path %>