config/routes.rb
require 'resque_web'

Rails.application.routes.draw do

  resources :turns

  resources :regions

  resources :local_participation_records

  resources :boards

  resources :users

  root 'boards#show'

  mount ResqueWeb::Engine => '/resque_web'

end

app/models/turn.rb
class Turn < ActiveRecord::Base
  belongs_to :user
  belongs_to :board
  belongs_to :local_participation_record

  attr_accessor :command

  def parse_command!
    cmd_name, cmd_args = message.split(/\s/, 2)

    case cmd_name
      when 'go' then move_user(user, local_participation_record, *cmd_args.split(/\s/))
      else invalid_command(cmd_args)
    end

    save!
  end

  private

  def move_user(user, participation_record, *args)
    self.command = 'go'
    newx, newy = [participation_record.xpos, participation_record.ypos]
    cmd_args = args
    if cmd_args.length > 0
      case cmd_args.first.downcase
        when 'up' then
          self.command += ' left'
          newy = newy - 1
        when 'right' then
          self.command += ' right'
          newx = newx + 1
        when 'down' then
          self.command += ' down'
          newy = newy + 1
        when 'left' then
          self.command += ' left'
          newx = newx - 1
      end
    end

    # reset if out of bounds
    newx = participation_record.xpos if newx < 0 or newx >= self.board.width
    newy = participation_record.ypos if newy < 0 or newy >= self.board.height
    self.xpos = newx
    self.ypos = newy
    participation_record.update!(xpos:newx, ypos:newy, num_moves: participation_record.num_moves + 1)
  end

  def invalid_command(*args)
    self.command = 'invalid'
  end
end

app/controllers/turns_controller.rb
class TurnsController < ApplicationController
  before_action :set_turn, only: [:show, :edit, :update, :destroy]

  # GET /turns
  # GET /turns.json
  def index
    @turns = Turn.all
  end

  # GET /turns/1
  # GET /turns/1.json
  def show
  end

  # GET /turns/new
  def new
    @turn = Turn.new
  end

  # GET /turns/1/edit
  def edit
  end

  # POST /turns
  # POST /turns.json
  def create
    @turn = Turn.new(turn_params)

    respond_to do |format|
      if @turn.save
        format.html { redirect_to @turn, notice: 'Turn was successfully created.' }
        format.json { render :show, status: :created, location: @turn }
      else
        format.html { render :new }
        format.json { render json: @turn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turns/1
  # PATCH/PUT /turns/1.json
  def update
    respond_to do |format|
      if @turn.update(turn_params)
        format.html { redirect_to @turn, notice: 'Turn was successfully updated.' }
        format.json { render :show, status: :ok, location: @turn }
      else
        format.html { render :edit }
        format.json { render json: @turn.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turns/1
  # DELETE /turns/1.json
  def destroy
    @turn.destroy
    respond_to do |format|
      format.html { redirect_to turns_url, notice: 'Turn was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turn
      @turn = Turn.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def turn_params
      params.require(:turn).permit(:user_id, :friend_username, :board_id, :command, :xpos, :ypos)
    end
end

app/helpers/turns_helper.rb
module TurnsHelper
end

app/views/turns/_form.html.erb
<%= form_for(@turn) do |f| %>
  <% if @turn.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@turn.errors.count, "error") %> prohibited this turn from being saved:</h2>

      <ul>
      <% @turn.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :friend_username %><br>
    <%= f.text_field :friend_username %>
  </div>
  <div class="field">
    <%= f.label :board_id %><br>
    <%= f.number_field :board_id %>
  </div>
  <div class="field">
    <%= f.label :command %><br>
    <%= f.text_field :command %>
  </div>
  <div class="field">
    <%= f.label :xpos %><br>
    <%= f.number_field :xpos %>
  </div>
  <div class="field">
    <%= f.label :ypos %><br>
    <%= f.number_field :ypos %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/turns/edit.html.erb
<h1>Editing Turn</h1>

<%= render 'form' %>

<%= link_to 'Show', @turn %> |
<%= link_to 'Back', turns_path %>

app/views/turns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Turns</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Friend username</th>
      <th>Board</th>
      <th>Command</th>
      <th>Xpos</th>
      <th>Ypos</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @turns.each do |turn| %>
      <tr>
        <td><%= turn.user_id %></td>
        <td><%= turn.friend_username %></td>
        <td><%= turn.board_id %></td>
        <td><%= turn.command %></td>
        <td><%= turn.xpos %></td>
        <td><%= turn.ypos %></td>
        <td><%= link_to 'Show', turn %></td>
        <td><%= link_to 'Edit', edit_turn_path(turn) %></td>
        <td><%= link_to 'Destroy', turn, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Turn', new_turn_path %>

app/views/turns/new.html.erb
<h1>New Turn</h1>

<%= render 'form' %>

<%= link_to 'Back', turns_path %>

app/views/turns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @turn.user_id %>
</p>

<p>
  <strong>Friend username:</strong>
  <%= @turn.friend_username %>
</p>

<p>
  <strong>Board:</strong>
  <%= @turn.board_id %>
</p>

<p>
  <strong>Command:</strong>
  <%= @turn.command %>
</p>

<p>
  <strong>Xpos:</strong>
  <%= @turn.xpos %>
</p>

<p>
  <strong>Ypos:</strong>
  <%= @turn.ypos %>
</p>

<%= link_to 'Edit', edit_turn_path(@turn) %> |
<%= link_to 'Back', turns_path %>