config/routes.rb
require 'resque_web'

Rails.application.routes.draw do

  resources :turns

  resources :regions

  resources :local_participation_records

  resources :boards

  resources :users

  root 'boards#show'

  mount ResqueWeb::Engine => '/resque_web'

end

app/models/region.rb
class Region < ActiveRecord::Base
  belongs_to :board
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  before_action :set_region, only: [:show, :edit, :update, :destroy]

  # GET /regions
  # GET /regions.json
  def index
    @regions = Region.all
  end

  # GET /regions/1
  # GET /regions/1.json
  def show
  end

  # GET /regions/new
  def new
    @region = Region.new
  end

  # GET /regions/1/edit
  def edit
  end

  # POST /regions
  # POST /regions.json
  def create
    @region = Region.new(region_params)

    respond_to do |format|
      if @region.save
        format.html { redirect_to @region, notice: 'Region was successfully created.' }
        format.json { render :show, status: :created, location: @region }
      else
        format.html { render :new }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regions/1
  # PATCH/PUT /regions/1.json
  def update
    respond_to do |format|
      if @region.update(region_params)
        format.html { redirect_to @region, notice: 'Region was successfully updated.' }
        format.json { render :show, status: :ok, location: @region }
      else
        format.html { render :edit }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regions/1
  # DELETE /regions/1.json
  def destroy
    @region.destroy
    respond_to do |format|
      format.html { redirect_to regions_url, notice: 'Region was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_region
      @region = Region.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def region_params
      params.require(:region).permit(:top_left_x, :top_left_y, :height, :width, :title, :description)
    end
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/regions/_form.html.erb
<%= form_for(@region) do |f| %>
  <% if @region.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@region.errors.count, "error") %> prohibited this region from being saved:</h2>

      <ul>
      <% @region.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :top_left_x %><br>
    <%= f.number_field :top_left_x %>
  </div>
  <div class="field">
    <%= f.label :top_left_y %><br>
    <%= f.number_field :top_left_y %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.number_field :height %>
  </div>
  <div class="field">
    <%= f.label :width %><br>
    <%= f.number_field :width %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/regions/edit.html.erb
<h1>Editing Region</h1>

<%= render 'form' %>

<%= link_to 'Show', @region %> |
<%= link_to 'Back', regions_path %>

app/views/regions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Regions</h1>

<table>
  <thead>
    <tr>
      <th>Top left x</th>
      <th>Top left y</th>
      <th>Height</th>
      <th>Width</th>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @regions.each do |region| %>
      <tr>
        <td><%= region.top_left_x %></td>
        <td><%= region.top_left_y %></td>
        <td><%= region.height %></td>
        <td><%= region.width %></td>
        <td><%= region.title %></td>
        <td><%= region.description %></td>
        <td><%= link_to 'Show', region %></td>
        <td><%= link_to 'Edit', edit_region_path(region) %></td>
        <td><%= link_to 'Destroy', region, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Region', new_region_path %>

app/views/regions/new.html.erb
<h1>New Region</h1>

<%= render 'form' %>

<%= link_to 'Back', regions_path %>

app/views/regions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Top left x:</strong>
  <%= @region.top_left_x %>
</p>

<p>
  <strong>Top left y:</strong>
  <%= @region.top_left_y %>
</p>

<p>
  <strong>Height:</strong>
  <%= @region.height %>
</p>

<p>
  <strong>Width:</strong>
  <%= @region.width %>
</p>

<p>
  <strong>Title:</strong>
  <%= @region.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @region.description %>
</p>

<%= link_to 'Edit', edit_region_path(@region) %> |
<%= link_to 'Back', regions_path %>